services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/vkr?schema=public
      - NODE_ENV=production
      - JWT_SECRET="asflnaskfnsafk2"
  postgres:
    image: postgres:17
    container_name: vkr_test_db
    restart: always
    environment:
      POSTGRES_USER: vkr_test_user
      POSTGRES_PASSWORD: vkr_test_password
      POSTGRES_DB: vkr_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 